name: Example to execute shell script
on: push
jobs:
  sample_main_job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "This is our first step within our job 1 of workflow 1"
      - name: Clone my repo
        uses: actions/checkout@v7
        with:
          ref: main
      - name: Execute some script
        run: |
          chmod +x script1.sh 
          ./script1.sh
