name: Extra binary example
on: push
jobs:
  sample_main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install binary
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay example
        run: cowsay -f dragon "Run for cover, I am a DRAGON…RAWR" >> dragon.txt
